# repo branches

branches:
  only:
  - master

# job environment

sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

# job phases

install:
  - pip install --editable .[test] .

script:
  - pylint forks
  - py.test -vv --cov --cov-branch --cov-report=term-missing

after_success:
  - coveralls --base_dir $TRAVIS_BUILD_DIR
